# Generated by Django 4.1.3 on 2023-01-19 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0008_books_author_brief'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_address_total_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='订单号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单价格')),
                ('is_pay', models.BooleanField(default=False, verbose_name='已支付')),
                ('returns', models.BooleanField(default=False, verbose_name='退货')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.address', verbose_name='地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='books.secondbooks', verbose_name='商品')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orders', to_field='trade', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
            },
        ),
    ]
