# Generated by Django 4.1.3 on 2023-01-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_unique_together'),
        ('books', '0008_books_author_brief'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cart',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='carts.cartitem', verbose_name='购物车单项'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='books.secondbooks', verbose_name='商品'),
        ),
    ]
