# Generated by Django 4.1.3 on 2023-02-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_returns_orders_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='courier_number',
            field=models.CharField(max_length=50, null=True, verbose_name='快递单号'),
        ),
    ]
