# Generated by Django 4.1.3 on 2023-01-06 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_books_author_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storagetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间')),
                ('iscancel', models.BooleanField(default=False, verbose_name='已删除')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='books.secondbooks', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '购物项',
                'verbose_name_plural': '购物项',
            },
        ),
    ]
