# Generated by Django 4.1.3 on 2022-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sendaddress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='发货地址'),
        ),
    ]
