# Generated by Django 4.1.3 on 2022-12-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_city_user_county_user_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='昵称'),
        ),
    ]
