# Generated by Django 4.1.3 on 2023-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_address_city_alter_address_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='total_address',
            field=models.CharField(default='湖南省长沙市', max_length=100, verbose_name='完整地址'),
            preserve_default=False,
        ),
    ]
