export default {
    BASE_URL: 'http://127.0.0.1:8000',
    // 注册
    API_REGISTER: '/users/register/',
    // 登录
    API_LOGIN: '/users/login/',
    // 退出
    API_LOGOUT: '/users/logout/',
    // 检测session信息
    API_CHECK: '/users/check/',
    // 轮播图
    API_CAROUSEL: '/manages/carousel/',
    // 分类
    API_CATEGORY: '/books/category/',
    // 好书推荐
    API_RECOMMENDBOOKS: '/books/hot_books/',
    // 图书售卖信息
    API_SECONDBOOKSLIST: '/books/booklist/',
    // 获取单个二手书信息
    API_SINGALBOOK: '/books/',
    // 获取运费
    API_GETSHIPPINGCOST: '/manages/transport/cost/',
    // 用户信息
    API_USERINFO:'/users/info/',
    // 修改昵称
    API_CHANGENICKNAME: '/users/nickname/',
    // 上传头像
    API_UPLOADAVATAR: '/users/avatar/',
    // 修改密码
    API_CHANGEPWD:'/users/pwd/',
    // 修改显示名
    API_CHANGENAME: '/users/name/',
    // 根据分类获取书籍
    API_CATEGORYBOOK: '/books/categoryBook/',
    // 购物车
    API_CART: '/carts/',
    // 用户地址管理
    API_ADDRESS: '/users/address/',
    // 订单
    API_ORDER: '/orders/',
    // 根据购物车获取商品清单
    API_CART_TO_ORDER_ITEMS: '/orders/items/',
    // 支付
    API_PAY: '/orders/pay/',
    // 校验支付
    API_CHECK_PAY: '/orders/check/',
    // 搜索
    API_SEARCH: '/books/search/',
    // 获取已购书籍
    API_PURCHASEDBOOKS: '/orders/purchasedBooks/',
    // 根据书籍名称查询
    API_SEARCH_BY_NAME: '/books/search_by_name/',
    // 根据冠检测查询分类
    API_SEARCH_CATEGORY: '/books/search_category/',
    // 操作原图书信息
    API_ORIGIN_BOOK: '/books/origin/',
    // 操作二手书信息
    API_SECONDHAND_BOOK: '/books/second/',
    // 绑定手机号
    API_BIND_PHONE: '/users/phone/',
    // 根据用户id获取其所有在售商品
    API_ALL_GOODS_BY_USER: '/books/idall/',
    // 交易信息
    API_TRANSACTIONS:'/orders/transactions/'
  }