# Generated by Django 4.1.3 on 2022-11-22 10:44

import apps.utils.image_storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('isbn', models.CharField(db_index=True, max_length=13, verbose_name='ISBN')),
                ('image', models.ImageField(storage=apps.utils.image_storage.ImageStorage(), upload_to='books/%Y/%m/', verbose_name='封面')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('translator', models.CharField(blank=True, max_length=100, null=True, verbose_name='译者')),
                ('press', models.CharField(max_length=50, verbose_name='出版社')),
                ('revision', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='版次')),
                ('published_date', models.DateField(verbose_name='出版年月')),
                ('page_numbers', models.PositiveSmallIntegerField(verbose_name='页数')),
                ('describe', models.CharField(max_length=1024, verbose_name='简介')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='定价')),
                ('stock', models.PositiveIntegerField(verbose_name='存货量')),
                ('sales', models.PositiveIntegerField(verbose_name='销售量')),
            ],
            options={
                'verbose_name': '原书信息',
                'verbose_name_plural': '原书信息',
            },
        ),
        migrations.CreateModel(
            name='CategoryFirst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='类名')),
            ],
            options={
                'verbose_name': '一级类别',
                'verbose_name_plural': '一级类别',
            },
        ),
        migrations.CreateModel(
            name='SecondBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='书名')),
                ('image', models.ImageField(storage=apps.utils.image_storage.ImageStorage(), upload_to='books/%Y/%m/', verbose_name='封面')),
                ('originbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondhandbooks', to='books.books', verbose_name='原书')),
            ],
            options={
                'verbose_name': '二手图书',
                'verbose_name_plural': '二手图书',
            },
        ),
    ]
