# Generated by Django 4.1.3 on 2022-11-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbooks',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='二手价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondbooks',
            name='returns',
            field=models.BooleanField(default=False, verbose_name='是否退货'),
        ),
        migrations.AddField(
            model_name='secondbooks',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='是否售出'),
        ),
        migrations.AddField(
            model_name='secondbooks',
            name='transit',
            field=models.BooleanField(default=False, verbose_name='运输中'),
        ),
        migrations.AlterField(
            model_name='books',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价'),
        ),
    ]
