# Generated by Django 4.1.3 on 2022-11-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_secondbooks_price_secondbooks_returns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='books',
            name='stock',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='books.categoryfirst', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='books',
            name='describe',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='books',
            name='page_numbers',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='页数'),
        ),
        migrations.AlterField(
            model_name='books',
            name='press',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='出版年月'),
        ),
    ]
