# Generated by Django 4.1.3 on 2022-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_sales_remove_books_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(db_index=True, max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
