# Generated by Django 4.1.3 on 2022-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_books_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbooks',
            name='ptime',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
    ]
