# Generated by Django 4.1.3 on 2022-12-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_secondbooks_ptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondbooks',
            name='ptime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
