# Generated by Django 4.1.3 on 2023-01-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_secondbooks_ptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_brief',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='作者简介'),
        ),
    ]
