# Generated by Django 4.1.3 on 2023-02-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_books_author_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbooks',
            name='remove',
            field=models.BooleanField(default=False, verbose_name='是否下架'),
        ),
    ]
