# Generated by Django 4.1.3 on 2022-11-29 20:10

import apps.utils.image_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=apps.utils.image_storage.ImageStorage(), upload_to='carousel/%Y/%m', verbose_name='轮播')),
                ('content', models.CharField(max_length=20, verbose_name='图片内容')),
                ('added_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播',
                'verbose_name_plural': '轮播',
            },
        ),
    ]
